### PR TITLE
Codeclimate & Editorconfig support

### PR DESCRIPTION
**Pull request by bhubbard**
Added support for CodeClimate set to use WordPress standards. Also added WordPress default `.editorconfig` file.

### CODE REVIEW

**Comment by lukecarbis** [comment]
@bhubbard Talk me through why this project should be using CodeClimate? We already use Travis for this sort of thing.

**Comment by bhubbard** [comment]
@lukecarbis CodeClimate is more of a linter style tool, it will run checks for css, markdown, js, php coding standards. It will provide an overall GPA score, and a list of issues by category. 

In fact CodeClimate will actually integrate with Travis-CI. 

https://docs.travis-ci.com/user/code-climate/
https://docs.codeclimate.com/docs/setting-up-test-coverage

**Comment by ntwb** [comment]
The `css-lint`, `scss-lint`, and `eslint` analysis engines **do not** support WordPress coding Standards 

I also don't see this changing anytime soon either, I'd suggest you remove those analysis engines from your Code Climate configurations as they will affect that _GPA_ significantly

**Comment by lukecarbis** [comment]
The other thing is ignoring the libraries.

**Comment by ntwb** [comment]
p.s. WordPress Coding Standards for CSS with stylelint and Js with ESLint can be found:
• https://github.com/ntwb/stylelint-config-wordpress
• https://github.com/ntwb/eslint-config-wordpress

**Pull request merged**
