### PR TITLE
BuddyPress Connector: Check for BP dependencies before blindly assuming they're available

### LINKED ISSUE #1516: BuddyPress connector can fatal in network admin
# Bug Report

```
Uncaught Error: Call to undefined function groups_get_group()
wp-content/plugins/stream/connectors/class-connector-buddypress.php:210
```

It appears that BuddyPress group functions are not available within network admin, likely because the Groups component isn't activated in the context of the site.
As a result, this may also be able to be triggered by enabling groups, performing actions, and then disabling groups. I haven't tested this.

## Expected Behavior

I'd expect it to gracefully degrade when BuddyPress groups functions aren't available.

## Actual Behavior

A fatal error is encountered.

## Steps to Reproduce the Problem

1. Have a Multisite network. Have BuddyPress & Stream Network Activated
2. Join a group
3. View the Stream network admin list
4. Receive fatal.

## System Information

- Stream plugin version: 4.0.0
- BuddyPress plugin version: 14.x
- WordPress version: Trunk
- PHP version: 7.4

### PR DESCRIPTION
**Pull request by dd32**
Fixes #1516.

Untested, this is just a visual patch from looking at the code.

# Checklist

- [ ] Project documentation has been updated to reflect the changes in this pull request, if applicable.
- [ ] I have tested the changes in the local development environment (see `contributing.md`).
- [ ] I have added phpunit tests.

## Release Changelog

- Fix: Avoid potential fatal errors when using BuddyPress and Stream.

## Release Checklist

- [ ] This pull request is to the `master` branch.
- [ ] Release version follows [semantic versioning](https://semver.org). Does it include breaking changes?
- [ ] Update changelog in `readme.txt`.
- [ ] Bump version in `stream.php`.
- [ ] Bump `Stable tag` in `readme.txt`.
- [ ] Bump version in `classes/class-plugin.php`.
- [ ] Draft a release [on GitHub](https://github.com/xwp/stream/releases/new).

### CODE REVIEW

**Comment by dd32** [comment]
This PR probably avoids the fatals, but the links in network admin might be incorrect too... It might be that the links should be using `get_admin_url( $blog_id, ... )` instead such as they go the correct location...

**Comment by tharsheblows** [comment]
@delawski @dd32 This fixes the fatal errors for me -- 

> This PR probably avoids the fatals, but the links in network admin might be incorrect too... It might be that the links should be using get_admin_url( $blog_id, ... ) instead such as they go the correct location... 

I think we should merge this now and I'll open another issue to update those links.

**Comment by tharsheblows** [comment]
Added issue for action links: https://github.com/xwp/stream/issues/1520

**Comment by dd32** [comment]
Thank you @tharsheblows!

**Pull request merged**
