### PR TITLE
Add a migration script for upgrading to Stream from 1.4.9

### LINKED ISSUE #733: Migrate Stream 1 to Stream 3?
I have a handful of clients whom did not make the jump to Stream 2 for one reason or another.  With the recent announcement of Stream 3 being brought back to local storage and no wordpress.com login needed, I would like to get them to Stream 3.  Testing with a site where the records aren't as important, I was hoping that the conversion process would detect the local storage of Stream 1 and perform the conversion, however it appears I was incorrect.  After the update, there was no prompt for conversion, and the current record display has much of the information missing.  The information that remains is the summary description, time stamp, and IP address.  The user, context, and action are either blank or n/a.  I updated a plugin afterwards of which no record was made.

I was wondering what the preferred method of upgrading from 1 to 3 might be, or if there is anything currently being made to streamline this process.  Thank you in advance for any assistance you can provide.

### PR DESCRIPTION
**Pull request by lukecarbis**
@marioknight Can you please test this branch out on one of your version 1.4.9 installs? Please take a backup first.

Resolves #733.

### CODE REVIEW

**Comment by MarioKnight** [comment]
I have performed the following steps on a 1.4.9 install:

* Downloaded ZIP of this pull request
* De-activated 1.4.9, installed ZIP of this pull request and activated
* It seemed to take a bit longer for the plugin activate page to load, however no errors were produced when it did
* Going to the Stream page does not prompt for an update

On the Stream page itself, all of the data look as it should except for the date field.  Every entry contains the following in the date:

`14 years ago`
`-0001/11/29`
`07:00:00 PM`

I've gone ahead and reverted back to 1.4.9 and restored the database from the backup.

Thank you for your continued work on this.  Please let me know if you'd like for me to do anything else on my end.

**Comment by Japh** [comment]
fwiw, I had problems migrating (from v2 to v3) when I was deactivating v2 and activating v3. But when I just updated the plugin, it worked flawlessly.

Not sure if that's what's going on here, but I thought it might be worth mentioning.

**Comment by lukecarbis** [comment]
@MarioKnight Great! That's what is supposed to happen (except the date thing). I'll try to fix that part today.

**Comment by lukecarbis** [comment]
screen shot 2015-09-02 at 09 44 07

Just for lolz.

**Comment by lukecarbis** [comment]
@MarioKnight Fixed.

**Pull request merged**
