### PR TITLE
Uploading changes to adapt code to PHP 8.1

### LINKED ISSUE #1349: PHP 8.1: PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated
# Bug Report

## Expected Behavior

No error message.

## Actual Behavior

```
PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/local/wordpress/wp-content/plugins/stream/classes/class-log.php on line 215
```

## Steps to Reproduce the Problem

1. Just logging in and traversing core admin pages.

## System Information

- Stream plugin version: 3.9.0
- WordPress version: 6.0
- PHP version: 8.1

### PR DESCRIPTION
**Pull request by davefx**
Fixes #1349 .

I've fixed all the deprecation warnings I've found when running my site against PHP 8.1.

# Checklist

- [x] Project documentation has been updated to reflect the changes in this pull request, if applicable.
- [x] I have tested the changes in the local development environment (see `contributing.md`).
- [ ] I have added phpunit tests.

## Release Changelog

- Fix: #1349, and other PHP-8.1 deprecation warnings 

## Release Checklist

- [ ] This pull request is to the `master` branch.
- [ ] Release version follows [semantic versioning](https://semver.org). Does it include breaking changes?
- [ ] Update changelog in `readme.txt`.
- [ ] Bump version in `stream.php`.
- [ ] Bump `Stable tag` in `readme.txt`.
- [ ] Bump version in `classes/class-plugin.php`.
- [ ] Draft a release [on GitHub](https://github.com/xwp/stream/releases/new).

Change `[ ]` to `[x]` to mark the items as done.

### CODE REVIEW

**Comment by simonhammes** [comment]
@davefx Can you fix the conflicts in this PR?

**Comment by davefx** [comment]
@simonhammes Conflicts resolved.
Thanks!

**Comment by delawski** [comment]
This will be superseded by #1494.

**Comment by delawski** [comment]
The PHP 8 compatibility issues have been addressed in 4.0.1 so I'm closing this PR.

**Pull request closed without merging**
