### PR TITLE
Fix namespace of Closure

### PR DESCRIPTION
**Pull request by szepeviktor**
Fix namespace of Closure

# Checklist

- [ ] Project documentation has been updated to reflect the changes in this pull request, if applicable.
- [ ] I have tested the changes in the local development environment (see `contributing.md`).
- [ ] I have added phpunit tests.

Please consider using @phpstan

### CODE REVIEW

**Review by kidunot89 — APPROVED** [review]
@szepeviktor Good catch :+1:

**Comment by szepeviktor** [comment]
> @szepeviktor Good catch 👍

@PHPStan is good!

**Comment by szepeviktor** [comment]
```bash
composer require --ignore-platform-reqs --dev szepeviktor/phpstan-wordpress
vendor/bin/phpstan analyse -c vendor/szepeviktor/phpstan-wordpress/extension.neon alerts/ classes/ connectors/ exporters/ includes/ stream.php -l 0
```

Levels go up to 8!

**Review by kasparsd — APPROVED** [review]

**Comment by kasparsd** [comment]
@kidunot89 Feel free to merge this whenever you're around.

**Pull request merged**
