### PR TITLE
Preparing Stream for Alternate Database Drivers

### PR DESCRIPTION
**Pull request by lukecarbis**
See #881. 

Moving here for extra work and testing.

### CODE REVIEW

**Comment by lukecarbis** [comment]
@dkotter Have you got an example Stream Add-On that uses the `wp_stream_db_driver` filter to use a different database?

**Comment by lukecarbis** [comment]
@dkotter ping.

**Comment by dkotter** [comment]
So we do have one that we are working on at 10up, but currently it's in a private repo. I believe we were waiting for these changes to land in Stream first before making that public, because without these changes, the plugin itself won't do anything.

Once these changes are live and we've thoroughly tested our plugin, we'll be happy to make that public and that can be used as an example of how to build an add-on.

**Comment by lukecarbis** [comment]
@dkotter I've reached out on WP Slack. If you could get me a copy to test this branch out privately - even if its a stripped back basic version - that would be much appreciated.

**Comment by lukecarbis** [comment]
Ping @dkotter

**Comment by tlovett1** [comment]
@lukecarbis we just sent you an invite to the repo.

**Comment by tlovett1** [comment]
Hey @lukecarbis when will this make it into a released version?

**Comment by lukecarbis** [comment]
Today. :)

**Comment by Japh** [comment]
🎉

**Pull request merged**
