### PR TITLE
Simplify the locate_plugin method

### LINKED ISSUE #731: Custom wp-content location causes activation error
On OpenShift:
```
Fatal error: Uncaught exception 'Exception' with message 
'Plugin dir is not inside of WP_CONTENT_DIR' in /var/lib/openshift/53f86113e0b8cd116c0001cf/app-root/data/plugins/stream/classes/class-plugin.php:214
 Stack trace: #0 /var/lib/openshift/53f86113e0b8cd116c0001cf/app-root/data/plugins/stream/classes/class-plugin.php(60): WP_Stream\Plugin->locate_plugin() 
#1 /var/lib/openshift/53f86113e0b8cd116c0001cf/app-root/data/plugins/stream/stream.php(37): WP_Stream\Plugin->__construct() 
#2 /var/lib/openshift/53f86113e0b8cd116c0001cf/app-root/data/current/wp-admin/plugins.php(153): include('/var/lib/opensh...') 
#3 /var/lib/openshift/53f86113e0b8cd116c0001cf/app-root/data/current/wp-admin/plugins.php(155): plugin_sandbox_scrape('stream/stream.p...') 
#4 {main} thrown in /var/lib/openshift/53f86113e0b8cd116c0001cf/app-root/data/plugins/stream/classes/class-plugin.php on line 214 
```

### PR DESCRIPTION
**Pull request by lukecarbis**
Support for alternative wp-content locations.

Resolves #731

### CODE REVIEW

**Comment by lukecarbis** [comment]
@szepeviktor (or anyone else) would you mind reviewing this PR before I merge it?

**Comment by szepeviktor** [comment]
Seems OK

**Comment by fjarrett** [comment]
FYI the method that was removed here was for WordPress.com VIP support. Which may not be needed anymore, but just wanted to clarify why it was there in the first place.

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
