### PR TITLE
Update list table design at smaller screen size

### LINKED ISSUE #804: Responsive List Table
The list table looks a bit broken below 783px:
stream

Related: https://make.wordpress.org/core/2015/08/08/list-table-changes-in-4-3/

### PR DESCRIPTION
**Pull request by lukecarbis**
Resolves #804.

@ocean90 Please review, let me know if this works for you. :)

### CODE REVIEW

**Comment by lukecarbis** [comment]
@chacha Can you please review this PR?

**Comment by chacha** [comment]
@lukecarbis Could not reproduce in trunk. Could reproduce in stable. Functionally it works.

I looked to see if there was a simple way we could make this happen without using the `!important`, but given the complexity of the overriding rule, I think its the best solution here.

**Comment by chacha** [comment]
Create `bugfix/issue-804a` that has been updated with the fixes to Travis.

**Comment by lukecarbis** [comment]
@chacha - Travis fixes have been merged into develop, and I've merged develop into this branch. Anything else needed before I test / merge this fix?

**Comment by chacha** [comment]
@lukecarbis I think you're good. I'll go ahead and delete the `bugfix/issue-804a` branch and you should be set to merge.

**Comment by lukecarbis** [comment]
@chacha Made a couple of CSS changes - could you please test? If you and Travis are okay with it, please merge.

**Comment by chacha** [comment]
Looks great! :+1:

**Pull request merged**
