### PR TITLE
Add Slack alert implementation

### PR DESCRIPTION
**Pull request by robbiet480**
Unlike the old "Stream to Slack" plugin that didn't have any kind of alerting options or rich notifications, this does. Rich notifications look like this:

screen shot on 2018-03-04 at 18_41_49

### CODE REVIEW

**Comment by lkraav** [comment]
Wow, nice. Unfortunately the development team here seems to be super-busy with other projects. Anybody here know what the future plans are for Stream?

Itmw, I will patch my copies with this, and test it on a couple of production situations. Will report back once done.

**Comment by DavidCramer** [comment]
@robbiet480 This is very nice. Would it be possible for you to clean up the code to adhere to the required coding standards so that they pass the build? 
It would be a great help and I would love to get onto testing this fully.

Thanks!

**Comment by lkraav** [comment]
Is the `.DS_Store` file merged intentionally?

**Comment by robbiet480** [comment]
Only thing I see is addition of `.DS_Store` to the .gitignore...

**Comment by DavidCramer** [comment]
ye, and that is intentional. oh well. The new PR is here https://github.com/xwp/stream/pull/970

**Pull request merged**
